USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE DATABASE SNOWPARK_DB;

USE DATABASE SNOWPARK_DB;

CREATE OR REPLACE SCHEMA STAGGING;
CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA TRANSFORMED;
CREATE OR REPLACE SCHEMA CURATED;

USE SCHEMA SNOWPARK_DB.STAGGING;

-- ---------- INDIA ----------

CREATE OR REPLACE TABLE INDIA_ORDERS (
    ORDER_ID STRING,
    ORDER_DATE DATE,
    CUSTOMER_NAME STRING,
    STATE STRING,
    CITY STRING
);

CREATE OR REPLACE TABLE INDIA_ORDER_DETAILS (
    ORDER_ID STRING,
    AMOUNT STRING,
    PROFIT STRING,
    QUANTITY STRING,
    CATEGORY STRING,
    SUB_CATEGORY STRING
);

CREATE OR REPLACE TABLE INDIA_SALES_TARGETS (
    ORDER_MONTH STRING,
    CATEGORY STRING,
    TARGET STRING
);

-- ---------- USA (PARQUET) ----------

CREATE OR REPLACE TABLE SNOWPARK_DB.STAGGING.USA_SALES_ORDER_CP (
    "Row ID" NUMBER,
    "Order ID" STRING,
    "Order Date" DATE,
    "Ship Date" DATE,
    "Ship Mode" STRING,
    "Customer ID" STRING,
    "Country" STRING,
    "City" STRING,
    "State" STRING,
    "Postal Code" STRING,
    "Region" STRING,
    "Product ID" STRING,
    "Category" STRING,
    "Sub-Category" STRING,
    "Product Name" STRING,
    "Sales" STRING,
    "Quantity" STRING,
    "Discount" STRING,
    "Profit" STRING
);


-- ---------- UK ----------

CREATE OR REPLACE TABLE UK_SALES_ORDER_CP (
    INVOICE_NO STRING,
    STOCK_CODE STRING,
    DESCRIPTION STRING,
    QUANTITY STRING,
    INVOICE_DATE STRING,
    UNIT_PRICE STRING,
    CUSTOMER_ID STRING,
    COUNTRY STRING
);

-- ---------- STORAGE ----------

CREATE OR REPLACE STORAGE INTEGRATION SNOWPARK_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'S3'
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::430602287367:role/snowflake-snowpark'
STORAGE_ALLOWED_LOCATIONS = ('s3://global-sales-snowpark-bucket/data/');


DESC INTEGRATION SNOWPARK_INT;

CREATE OR REPLACE STAGE SNOWPARK_STAGE
STORAGE_INTEGRATION = SNOWPARK_INT
URL = 's3://global-sales-snowpark-bucket/data/';
  
ls @SNOWPARK_STAGE;
